apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: cjsqudwns/app:d5eabfb
          ports:
            - protocol: TCP
              containerPort: 8080
          # env:
          #   - name: SPRING_DATASOURCE_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: app-config
          #         key: db-url
          #   - name: SPRING_DATASOURCE_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: app-secret
          #         key: db-password
