apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080 # 원하는 포트 설정 가능, 또는 생략 시 클러스터가 자동 할당
  type: NodePort
